<?php
/**
 * Created by PhpStorm.
 * User: TEC-HOUSE
 * Date: 01/31/2019
 * Time: 05:02 م
 */

namespace Mechax\Resources;

use System\Classes\PluginBase;

class Plugin extends PluginBase
{
    public function pluginDetails()
    {
     //return parent::pluginDetails(); // TODO: Change the autogenerated stub
        return [
            'name' => 'Mechax',
            'description' => 'Provides company resources',
            'author' => 'Refaat Bitar',
            'icon' => 'icon-leaf',
        ];
    }

    public function registerComponents()
    {
     //   return parent::registerComponents(); // TODO: Change the autogenerated stub
        return [
            '\Mechax\Resources\Components\Links' => 'resourcesLinks',
        ];
    }
}